using Midway_Assessment.BusinessLogicLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Midway_Assessment.WebPages
{
    public partial class Equipment : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            try
            {
                EquipmentBL objEquipBL = new EquipmentBL();
                gvEquipment.DataSource = objEquipBL.ReadAllData(Request.MapPath(@"~\Database\Equipment.csv"));
                gvEquipment.DataBind();
            }
            catch (Exception ex)
            {
                ThrowException(ex.Message);
            }
        }

        protected void btnDelete_Click(object sender, EventArgs e)
        {
            
        }
        //private void Page_Error(object sender, EventArgs e)
        //{
        //    // Get last error from the server
        //    Exception exc = Server.GetLastError();

        //    // Handle exceptions generated by Button 1
        //    if (exc is InvalidOperationException)
        //    {
        //        // Pass the error on to the Generic Error page
        //        Server.Transfer("Error.aspx", true);

        //    }

        //    // Handle exceptions generated by Button 2
        //    else if (exc is ArgumentOutOfRangeException)
        //    {
        //        // Give the user some information, but
        //        // stay on the default page
        //        Response.Write("<h2>Default Page Error</h2>\n");
        //        Response.Write("<p>Provide as much information here as is " +
        //          "appropriate to show to the client.</p>\n");
        //        Response.Write("Return to the <a href='Default.aspx'>" +
        //            "Default Page</a>\n");

        //        // Clear the error from the server
        //        Server.ClearError();
        //    }
        //    else
        //    {
        //        // Give the user some information, but
        //        // stay on the default page
        //        Response.Write("<h2>Default Page Error</h2>\n");
        //        Response.Write("<p>Provide as much information here as is " +
        //          "appropriate to show to the client.</p>\n");
        //        Response.Write("Return to the <a href='Default.aspx'>" +
        //            "Default Page</a>\n");

        //        // Clear the error from the server
        //        Server.ClearError();
        //    }
        //}
        void ThrowException(string exception)
        {

            Response.Write("<h2>Error Page</h2>\n");
            Response.Write("<p>"+exception+"</p>\n");
            Response.Write("==========================================");
            
        }
    }
}